<?php

namespace easy;

/**
 * @author xiaoyaor
 *
 */
class Hash {

    /**
     * 插件文件夹
     * @var string
     */
    public static $addonsDir = "addons";
    /**
     * 插件名称
     * @var string
     */
    public static $addonsName = "";
    /**
     * 遍历的目录
     * @var string
     */
    public static $appFolder = "";

    /**
     * 忽略的文件夹及文件
     * @var string
     */
    public static $ignoreFilePaths = [ '.', '..', '.git', '.idea', 'runtime', '启动.bat','vendor','public/assets/libs'];

    public function __construct($name = '')
    {
        self::$addonsName=$name;
    }

    public static function start() {
        $AppPath = root_path().self::$addonsName;
        Hash::$appFolder = $AppPath;
        self::$addonsName?$destManifestPath = root_path().self::$addonsName.DIRECTORY_SEPARATOR."hash.php":$destManifestPath = root_path()."hash.php";
        $manifestHandle = fopen ( $destManifestPath, "w+" );// dest file handle
        Hash::writeMaifestHeader ( $manifestHandle );// write header
        Hash::traverse ( $AppPath, $manifestHandle );// write md5
        Hash::writeMaifestFooter ( $manifestHandle );// write footer
        fclose ( $manifestHandle );// close file
    }

    /**
     * 遍历应用根目录下的文件，并生成对应的文件长度及md5信息
     *
     * @param string $AppPath
     *        	应用根目录，如：xxx/xxx/analytics
     * @param string $destManifestPath
     *        	生成的manifest文件存放位置的文件句柄
     */
    public static function traverse($AppPath, $manifestHandle) {
        if (! file_exists ( $AppPath )) {
            printf ( $AppPath . " does not exist!" );
            return;
        }
        if (! is_dir ( $AppPath )) {
            printf ( $AppPath . " is not a directory!" );
            return;
        }
        if (! ($dh = opendir ( $AppPath ))) {
            printf ( "Failure while read diectory!" );
            return;
        }

        // read files
        while ( ($file = readdir ( $dh )) != false ) {
            $subDir = $AppPath . DIRECTORY_SEPARATOR . $file;

            if (in_array($file, (array)self::$ignoreFilePaths) ) {
                continue;
            } else if (is_dir ( $subDir )) {
                // rescure
                Hash::traverse ( $subDir, $manifestHandle );
            } else {
                // Sub is a file.
                Hash::writeOneFieToManifest ( $subDir, $manifestHandle );
            }
        }

        // close dir
        closedir ( $dh );
    }

    /**
     * 写一个文件的md5信息到文件中
     *
     * @param string $filePath
     * @param resource $fileHandle
     */
    public static function writeOneFieToManifest($filePath, $fileHandle) {
        if (! file_exists ( $filePath )) {
            return;
        }

        $relativePath = str_replace ( Hash::$appFolder . DIRECTORY_SEPARATOR, '', $filePath );
        $relativePath = str_replace ( "\\", "/", $relativePath );

        // ignore tmp directory
        if (strpos ( $relativePath, "tmp/" ) === 0) {
            return;
        }

        $fileSize = filesize ( $filePath );
        $fileMd5 = @md5_file ( $filePath );

        $content = "\t\t";
        $content .= '"';
        $content .= $relativePath;
        $content .= '"';
        $content .= ' => array("';
        $content .= $fileSize;
        $content .= '","';
        $content .= $fileMd5;
        $content .= '"),';
        $content .= "\n";

        if (! fwrite ( $fileHandle, $content )) {
            print ($filePath . " can not be written!") ;
        }
    }

    /**
     * 在manifes文件中写入头信息
     *
     * @param resource $fileHandle
     */
    public static function writeMaifestHeader($fileHandle) {
        $header = "<?php";
        $header .= "\n";
        $header .= "// This file is automatically generated";
        $header .= "\n";
        $header .= "namespace test;";
        $header .= "\n";
        $header .= "class MyFile {";
        $header .= "\n";
        $header .= "\tstatic \$allFiles=array(";
        $header .= "\n";

        if (! fwrite ( $fileHandle, $header )) {
            printf ( "Failure while write file header." );
        }
    }

    /**
     * 在manifes文件中写入尾部信息
     *
     * @param resource $fileHandle
     */
    public static function writeMaifestFooter($fileHandle) {
        $footer = "\t);";
        $footer .= "\n";
        $footer .= "}";
        $footer .= "\n";

        if (! fwrite ( $fileHandle, $footer )) {
            printf ( "Failure while write file header." );
        }
    }
}